name: Deploy Website

on:
  push:
    branches:
      - main  # Adjust the branch name as needed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Create known_hosts file
        run: mkdir -p ~/.ssh && touch ~/.ssh/known_hosts
      
      - name: Add server to known_hosts
        run: |
          ssh-keyscan -t rsa ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts
      
      - name: Deploy to server
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key.pem
          chmod 600 private_key.pem
          rsync -avz --delete -e "ssh -i private_key.pem" ${{ github.workspace }}/ sbzdev@${{ secrets.SERVER_IP }}:domains/sbz95.dev/public_html
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}