name: Deploy Website

on:
  push:
    branches:
      - main  # Adjust the branch name as needed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Create known_hosts file
        run: mkdir -p ~/.ssh && touch ~/.ssh/known_hosts
      
      - name: Add server to known_hosts
        run: |
          ssh-keyscan -t rsa ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts
      
      - name: Deploy to server
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | ssh -i - sbzdev@${{ secrets.SERVER_IP }} 'mkdir -p domains/sbz95.dev/public_html && cat > /tmp/deploy.tar.gz && tar -xzvf /tmp/deploy.tar.gz -C domains/sbz95.dev/public_html && rm /tmp/deploy.tar.gz'
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}