name: Deploy Website

on:
  push:
    branches:
      - main  # Adjust the branch name as needed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Deploy to server
        run: |
          ssh-keyscan -t rsa ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts
          rsync -avz --delete -e "ssh -i ${{ secrets.SSH_PRIVATE_KEY }}" ${{ github.workspace }}/ sbzdev@${{ secrets.SERVER_IP }}:domains/sbz95.dev/public_html
